version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: blueflag/client-build:0.0.7

    steps:
      - checkout

      - restore_cache:
          keys: ['deps-{{ checksum "yarn.lock" }}']

      - run: yarn prep

      - save_cache:
          key: deps-{{ checksum "yarn.lock" }}
          paths: ['packages/node_modules']

      - run: git diff | cat
      - run: test -z "$(git status --porcelain)"
      - run: yarn test-all

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
